### ISSUE TITLE
Add a contact page 

### ISSUE THREAD

**Issue by StatsRhian** [The-Strategy-Unit/nhp_project_information#1]
We have an email address mentioned on [one of the pages](https://connect.strategyunitwm.nhs.uk/nhp/project_information/modelling_methodology/baseline_data_validation.html). (mlcsu.nhpanalytics@nhs.net).

Perhaps we should have a general contact page.

Could also encourage the use of GitHub issues to raise concerns / requests?

**Comment by yiwen-h** [comment]
Contact page not working! Investigate bug
