### ISSUE TITLE
Be more specific about unique run names

### ISSUE THREAD

**Issue by matt-dray** [The-Strategy-Unit/nhp_project_information#151]
Scenario names are not always unique, which can make it awkward for us to do things like 'create new from existing' from someone else's account in the inputs app. For example, if you wanted to do an NDG1 version of a scenario that isn't the latest create datetime for that scenario name (e.g. they want 'scenario-x' from 11:00 rather than the later 12:00 version). There's no way to select an earlier run of a non-unique scenario name.

We have [guidance](https://connect.strategyunitwm.nhs.uk/nhp/project_information/user_guide/naming_scenarios.html), but it's not being followed exactly as we'd expect. There are several things we could do, see https://github.com/The-Strategy-Unit/nhp_planning/issues/118. In project information we should be more clear about using _unique_ names. Maybe even in a callout at the very top of the page.

**Comment by JenTWood** [comment]
Suggested in the MRM meeting that the guidance could include information on how to rename their runs, so if they haven't followed the guidance, we can more easily tell them to go and change the names restrospectively
