### ISSUE TITLE
Detailed explanation of binomial thinning

### ISSUE THREAD

**Issue by yiwen-h** [The-Strategy-Unit/nhp_project_information#156]
Model v3.1 introduces a new methodology for sampling, using binomial thinning. We have done thorough QA on it - results are largely the same - but the step counts/ waterfall charts may look quite different. Prepare thorough documentation and explanation

**Comment by StatsRhian** [comment]
Assuming we want a short sentence in the release notes and updating places where we describe the model [such as here](https://connect.strategyunitwm.nhs.uk/nhp/project_information/modelling_methodology/modelling_uncertainty.html#handling-uncertainty)?
