### ISSUE TITLE
Be consistent with website subheadings

### ISSUE THREAD

**Issue by StatsRhian** [The-Strategy-Unit/nhp_project_information#43]
Some of our subsections have got landing pages linked - others don't (e.g. User Guide)

I think that our subsections should either all link to a landing page, or not.

Leaning _slightly_ towards never having landing page since I'm worried that users might not spot those pages, although not strong on this.

![subsection-headings](https://github.com/The-Strategy-Unit/nhp_project_information/assets/7017740/8c858f22-ba8b-4d0d-8f2e-7686ea426c17)

**Comment by StatsRhian** [comment]
Any thoughts @yiwen-h?

**Comment by yiwen-h** [comment]
Yup makes sense! I don't mind either way but consistency is important. So let's default to never having landing page.
