### ISSUE TITLE
Remove KH03 and theatres from Data Summary page

### ISSUE THREAD

**Issue by yiwen-h** [The-Strategy-Unit/nhp_project_information#45]
https://connect.strategyunitwm.nhs.uk/nhp/project_information/modelling_methodology/data_summary.html

**Comment by StatsRhian** [comment]
You might also want to remove references to KH03 data in the [repo digram](https://connect.strategyunitwm.nhs.uk/nhp/project_information/software_implementation/components-overview.html)
