### ISSUE TITLE
Update age groups in 'parsing model results files'

### ISSUE THREAD

**Issue by matt-dray** [The-Strategy-Unit/nhp_project_information#78]
Need to update [the 'parsing model results files' page](https://connect.strategyunitwm.nhs.uk/nhp/project_information/user_guide/results.html) to match the upcoming [age group changes](https://github.com/The-Strategy-Unit/nhp_model/issues/175) in v2.1.

**Comment by yiwen-h** [comment]
I want to replace the parsing mode results files page with the nhp_results package when it's ready! but yes need to update this for now
